# Generated by Django 4.2.4 on 2023-10-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unidades', models.PositiveIntegerField()),
                ('costo_unitario', models.PositiveIntegerField()),
                ('nombre_articulo', models.CharField(max_length=255)),
                ('codigo_articulo', models.PositiveIntegerField()),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('total', models.PositiveIntegerField()),
            ],
        ),
    ]
