# Generated by Django 4.2.4 on 2023-10-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacionesChina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pedido', models.PositiveBigIntegerField()),
                ('costo_envio', models.PositiveBigIntegerField()),
                ('tasa_aduana', models.PositiveBigIntegerField()),
                ('iva', models.PositiveBigIntegerField()),
                ('total_impuestos', models.PositiveBigIntegerField()),
                ('total_compra', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='importacion',
            name='total',
        ),
    ]
