# Generated by Django 4.2.4 on 2023-10-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacionesChina', '0003_rename_total_compra_resultado_total_compra_clp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importacion',
            name='nombre_proveedor',
        ),
        migrations.AddField(
            model_name='importacion',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='importacion',
            name='proveedor',
            field=models.CharField(default='Proveedor Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='nombre_articulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='tasa_aduana',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='total_compra_clp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='total_compra_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='total_impuestos',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
