# Generated by Django 4.2.4 on 2023-10-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacionesChina', '0004_remove_importacion_nombre_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacion',
            name='nombre_articulo',
            field=models.CharField(default='Nombre Desconocido', max_length=100),
        ),
    ]
