# Generated by Django 4.2.4 on 2023-10-15 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importacionesChina', '0006_alter_importacion_nombre_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='importacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='importacionesChina.importacion'),
            preserve_default=False,
        ),
    ]
