# Generated by Django 4.2.4 on 2023-10-16 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importacionesChina', '0007_resultado_importacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='importacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importacionesChina.importacion'),
        ),
    ]
