# Generated by Django 4.2.4 on 2023-10-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacionesChina', '0008_alter_resultado_importacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='iva',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='tasa_aduana',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='total_compra_clp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='total_impuestos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='total_pedido',
            field=models.IntegerField(),
        ),
    ]
